#!/usr/bin/env bash

acedf="$1"
arg2="$2"
arg3="$3"
MEOWVERSION="1.0.1"
MEOWPATH=~/.meow
MEOWBACKUP=~/.cache/meow.bak
ac="meow "

function pass(){
	:
}
function meowecho(){
	echo "meow: ${1}"
}
function meowpass(){ # Alias to pass
	pass
}
function meowautoclear(){
	clear || meowpass
}
function meowpull(){
	type="$1"
	if [[ "$type" == "linux" ]]; then
		curl https://raw.githubusercontent.com/VBPROGER/meow/main/src/meow>~/.local/bin/meow 2>/dev/null;
		chmod u+x ~/.local/bin/meow
	elif [[ "$type" == "darwin" ]]; then
		# Note: On darwin, you need to install cUrl by yourself, because it's not installed by default
		curl https://raw.githubusercontent.com/VBPROGER/meow/main/src/meow>~/meow 2>/dev/null;
		chmod u+x ~/meow
	else
		meowecho 'Something went wrong, failed to determine OS type'
	fi
}

mkdir -p $MEOWPATH 2>/dev/null

if [[ "$acedf" == "" ]]; then
	while true; do
		read -rp "" "meow"
		echo "$meow"
	done
elif [[ "$acedf" == "mew" ]]; then
	meowecho "processing..."
	to_download=$arg2
	meowecho "downloading..."
	mkdir -p "$MEOWPATH/${to_download}" 2>/dev/null
	meowecho "downloading \"main\" file..."
	/usr/bin/env curl "https://raw.githubusercontent.com/VBPROGER/meow/main/pkg/$to_download/main" > "${MEOWPATH}/${to_download}/main" 2>/dev/null
	/usr/bin/chmod +x "${MEOWPATH}/${to_download}"/main 2>/dev/null
	meowecho "downloading \"todownload\" file..."
	/usr/bin/env curl "https://raw.githubusercontent.com/VBPROGER/meow/main/pkg/$to_download/todownload" > "${MEOWPATH}/${to_download}"/todownload 2>/dev/null
	/usr/bin/chmod +x ${MEOWPATH}/${to_download}/todownload 2>/dev/null
	meowecho "checking required file(s)/folder(s) file..."
	for line in $(cat ${MEOWPATH}/${to_download}/todownload); do
		meowecho "downloading \"$line\" file by request..."
		/usr/bin/env curl "https://raw.githubusercontent.com/VBPROGER/meow/main/pkg/$to_download/$line" > "${MEOWPATH}/${to_download}/$line" 2>/dev/null
		/usr/bin/chmod +x "${MEOWPATH}/${to_download}/$line" 2>/dev/null
	done
elif [[ "$acedf" == "help" ]]; then
	meowecho "--- meow v${MEOWVERSION} ---
welcome!

-..- CMD HELP -..-

${ac}help [*anyarguments]
	shows list of commands,
	info and more.
${ac}mew <name> [*anyarguments]
	download/install package by
	name using the \"mew\" method.
	downloading/installing folders
	is not allowed, if is even mentioned
	in the \"todownload\" file.
	if \"force\" argument is not
	equals \"null\" then meow
	will ignore ~~all~~ folder errors.
${ac}run <name> [*anyarguments]
	make the package executable
	and launch it, if possible.
	if package with name <name>
	does not exist, it will show
	error. there's no way yet
	to hide this error.
${ac}del <name> [-s] || [--silent] [*anyarguments]
	will attempt to delete package
	with name <name>, if not installed,
	will show error (if -s || --silent
	argument is not used).
${ac}ulist [-s] || [--strip] [*anyarguments]
	get list of aviable packages.
	if -s is used, then it will
	not create newline at the end
${ac}clean <-f> || <--force>; [-c] || [--cached] [*anyarguments]
	delete all installed packages
	from the current machine.
	if [-c] || [--cached] arguments is used,
	then cached reserve copy of self, if
	exists, will be removed (usually created
	during updates (pullme))
${ac}pullme [-u] || [--unsafe] [*anyarguments]
       update self to the newest
	MEOWVERSION of MEOW package manager.
	if [-u] || [--unsafe] argument
	is used, then script will not
	copy itself to the cache folder.

-..- EXAMPLES FOR CMD -..-

${ac}mew mycoolpackage
# will download package with name 'mycoolpackage'.
${ac}ulist --strip
# will show all packages (no newline at the end)
${ac}del firstpkg
# will delete package with the name \"firstpkg\"
${ac}clean -f
# clean all packages (wipe)
${ac}clean -f -c
# clean all packages (wipe) and deleted
# cached reserve copy of self
${ac}pullme
# update self
${ac}pullme -u
# update self (don't create self backup)
"
elif [[ "$acedf" == "ulist" ]]; then
	for filename in "${MEOWPATH?:}"/*; do
			printf "%s\n" "${filename}"
		done
		if [[ ("$arg2" != "-s") && ("$arg2" != "--strip") ]]; then
			echo ''
		fi
elif [[ "$acedf" == "del" ]]; then
	if [[ "${arg2}" != '' ]] && [ -d "${MEOWPATH:?}/${arg2}" ]; then
		rm -rf "${MEOWPATH:?}/${arg2}" 2>/dev/null
		if [[ ! ("$arg3" == '-s' || "$arg3" == '--silent') ]]; then
			meowecho "successfully removed pkg with name '${arg2}'"
		fi
	else
		if [[ ! ("$arg3" == '-s' || "$arg3" == '--silent') ]]; then
			meowecho "failed to remove pkg with name '${arg2}'"
		fi
	fi
elif [[ "$acedf" == "clean" ]]; then
	if [[ "$arg2" == '-f' || "$arg2" == '--force' ]]; then
		for filename in "${MEOWPATH}"/*; do
			rm -rf "$filename"
		done
	fi
	if [[ "$arg2" == '-c' || "$arg2" == '--cache' || "$arg3" == '-c' || "$arg3" == '--cache' ]]; then
		# Also delete cached backup
		# if exists (not really safe!)
		if [[ -f "$MEOWBACKUP" ]]; then
			rm -f "$MEOWBACKUP" 2>/dev/null
		fi
	fi
elif [[ "$acedf" == "pullme" ]]; then
	meowecho 'Pulling the newest MEOW MEOWVERSION...'
	if [[ ! ("$arg3" == '-u' || "$arg3" == '--unsafe') ]]; then
		meowecho "Creating self backup at $MEOWBACKUP"
		cp "$0" "$MEOWBACKUP"
	fi
	if [[ "$arg2" == '' ]]; then
		if [[ "$OSTYPE" == "linux-gnu"* ]]; then
				meowpull linux
		elif [[ "$OSTYPE" == "darwin"* ]]; then
				meowpull darwin
		elif [[ "$OSTYPE" == "cygwin" ]]; then
				meowpull linux
		elif [[ "$OSTYPE" == "msys" ]]; then
				meowpull linux
		elif [[ "$OSTYPE" == "win32" ]]; then
				meowecho "Windows is not supported"
		elif [[ "$OSTYPE" == "freebsd"* ]]; then
				meowpull linux
		else
				meowecho 'Unsupported OS type: '"\"${OSTYPE}\""
		fi
	else
		meowpull "$arg2"
	fi
	meowecho 'Done!'
elif [[ "$acedf" == "run" ]]; then
	if [[ "$arg2" != '' ]]; then
		chmod +x "$MEOWPATH/$arg2/main"
		# shellcheck disable=SC1090
		. "$MEOWPATH/$arg2/main"
	else
		meowecho "package with name '${arg2}' does not exist."
	fi
else
	meowecho "welcome to meow, v${MEOWVERSION}."
fi